Fix crash with ini_set when opcache is enabled on CLI
The error was:
FatalThrowableError: ini_set() expects parameter 2 to be string, int given

This happened during the cache:clear step